const express = require('express');
const { verifyToken } = require('../middlewares/auth.middleware');
const { validateRequestHeaders } = require('../middlewares/validation.middleware');
const userRoutes = require('./user.route');
const userSuspensionRoutes = require('./user-suspension.route');
const authRoutes = require('./auth.route');
const countryRoutes = require('./country.route');
const cityRoutes = require('./city.route');
const areaRoutes = require('./area.route');
const categoryRoutes = require('./category.route');
const subcategoryRoutes = require('./subcategory.route');
const thirdcategoryRoutes = require('./thirdcategory.route');
const subcategoryAttributeRoutes = require('./subcategory-attribute.route');
const productAttributeRoutes = require('./product-attribute.route');
const articleRoutes = require('./article.route');
const commentRoutes = require('./comment.route');
const likeRoutes = require('./like.route');
const dislikeRoutes = require('./dislike.route');
const productRoutes = require('./product.route');
const currencyRoutes = require('./currency.route');
const adRoutes = require('./ad.route');
const adpackageRoutes = require('./adpackage.route');
const userAdPackageRoutes = require('./user-adpackage.route');
const statusRoutes = require('./status.route');
const favouriteProductRoutes = require('./favourite-product.route');
const savedSearchRoutes = require('./saved-search.route');
const messageRoutes = require('./message.route');
const chatRoutes = require('./chat.route');
const notificationRoutes = require('./notification.route');
const paidadRoutes = require('./paidad.route');
const paidadSettingsRoutes = require('./paidad-settings.route');
const uploadFileRoutes = require('./upload-file.route');
const productFeedbackRoutes = require('./product-feedback.route');
const settingsRoutes = require('./settings.route');
const archiveRoutes = require('./archive.route');
const reportRoutes = require('./report.route');
const router = express.Router();

router.use('/ad', adRoutes);
router.use('/adpackage', verifyToken, validateRequestHeaders, adpackageRoutes);
router.use('/auth', authRoutes);
router.use('/user', verifyToken, validateRequestHeaders, userRoutes);
router.use('/user-suspension', verifyToken, validateRequestHeaders, userSuspensionRoutes);
router.use('/upload-file', verifyToken, validateRequestHeaders, uploadFileRoutes);
router.use('/country', countryRoutes);
router.use('/city', verifyToken, validateRequestHeaders, cityRoutes);
router.use('/area', verifyToken, validateRequestHeaders, areaRoutes);
router.use('/status', verifyToken, validateRequestHeaders, statusRoutes);
router.use('/currency', verifyToken, validateRequestHeaders, currencyRoutes);
router.use('/category', verifyToken, validateRequestHeaders, categoryRoutes);
router.use('/subcategory', verifyToken, validateRequestHeaders, subcategoryRoutes);
router.use('/thirdcategory', verifyToken, validateRequestHeaders, thirdcategoryRoutes);
router.use('/subcategory-attribute', verifyToken, validateRequestHeaders, subcategoryAttributeRoutes);
router.use('/product-attribute', verifyToken, validateRequestHeaders, productAttributeRoutes);
router.use('/product-feedback', verifyToken, validateRequestHeaders, productFeedbackRoutes);
router.use('/product', verifyToken, validateRequestHeaders, productRoutes);
router.use('/useradpackage', verifyToken, validateRequestHeaders, userAdPackageRoutes);
router.use('/favouriteproduct', verifyToken, validateRequestHeaders, favouriteProductRoutes);
router.use('/savedsearch', verifyToken, validateRequestHeaders, savedSearchRoutes);
router.use('/article', verifyToken, validateRequestHeaders, articleRoutes);
router.use('/comment', verifyToken, validateRequestHeaders, commentRoutes);
router.use('/like', verifyToken, validateRequestHeaders, likeRoutes);
router.use('/dislike', verifyToken, validateRequestHeaders, dislikeRoutes);
router.use('/chat', verifyToken, validateRequestHeaders, chatRoutes);
router.use('/message', verifyToken, validateRequestHeaders, messageRoutes);
router.use('/notification', verifyToken, validateRequestHeaders, notificationRoutes);
router.use('/paidad', verifyToken, validateRequestHeaders, paidadRoutes);
router.use('/paidad-settings', verifyToken, validateRequestHeaders, paidadSettingsRoutes);
router.use('/settings', verifyToken, validateRequestHeaders, settingsRoutes);
router.use('/archive', verifyToken, validateRequestHeaders, archiveRoutes);
router.use('/report', verifyToken, validateRequestHeaders, reportRoutes);
// router.use('/payment', verifyToken, validateRequestHeaders, notificationRoutes);

module.exports = router;
